# Generated by Django 5.2.17 on 2026-08-10 16:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("username", models.CharField(max_length=150)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login success"),
                            ("LOGIN_FAILED", "Login failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_RESET", "Password reset"),
                            ("ACCOUNT_LOCKED", "Account locked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "event_type", "timestamp"],
                        name="security_se_ip_addr_7aec1a_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="security_se_ip_addr_7e6b32_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("BRUTE_FORCE", "Brute force"),
                            ("MULTIPLE_ACCOUNTS", "Multiple accounts"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious activity"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("username", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField()),
                (
                    "risk_score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "related_events",
                    models.ManyToManyField(
                        blank=True, related_name="alerts", to="security.securityevent"
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_type", "ip_address", "detected_at"],
                        name="security_al_alert_t_fdd4df_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="security_al_severit_f7a7c0_idx"
                    ),
                ],
            },
        ),
    ]
